:-
:: User docs
::
~
:: Developer docs
::
:~  :-  %hark-store
    :~  [/overview/udon 'Overview']
        [/types/udon 'Data Types']
        [/pokes/udon 'Pokes']
        [/paths/udon 'Subscription Paths']
        [/scry/udon 'Scry Endpoints']
    ==
    :-  %settings-store
    :~  [/overview/udon 'Overview']
        [/types/udon 'Data Types']
        [/pokes/udon 'Pokes']
        [/paths/udon 'Subscription Paths']
        [/scry/udon 'Scry Endpoints']
    ==
==
